# Custom node-exporter collecting GPU metrics from dcgm-exporter.
# Refer: https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/prometheus/node-exporter-ds.yml
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: node-exporter
spec:
  template:
    metadata:
      labels:
        app: node-exporter
      name: node-exporter
      annotations:
        ad.datadoghq.com/node-exporter.check_names: |
          ["prometheus"]
        ad.datadoghq.com/node-exporter.init_configs: |
          [{}]
        ad.datadoghq.com/node-exporter.instances: |
          [
            {
              "prometheus_url": "http://%%host%%:9100/metrics",
              "namespace": "nvidia",
              "metrics": ["dcgm_thermal_violation", "dcgm_sm_clock", "dcgm_power_violation", "dcgm_power_usage", "dcgm_memory_clock", "dcgm_mem_copy_utilization", "dcgm_gpu_utilization", "dcgm_enc_utilization", "dcgm_dec_utilization", "dcgm_gpu_temp"]
            }
          ]
    spec:
      nodeSelector:
        hardware-type: NVIDIAGPU
      containers:
      - image: quay.io/prometheus/node-exporter:v0.15.2
        name: node-exporter
        args:
        - "--web.listen-address=0.0.0.0:9100"
        - "--path.procfs=/host/proc"
        - "--path.sysfs=/host/sys"
        - "--collector.textfile.directory=/run/prometheus"
        ports:
        - name: metrics
          containerPort: 9100
          hostPort: 9100
        resources:
          requests:
            memory: 30Mi
            cpu: 100m
          limits:
            memory: 50Mi
            cpu: 200m
        volumeMounts:
        - name: proc
          readOnly:  true
          mountPath: /host/proc
        - name: sys
          readOnly: true
          mountPath: /host/sys
        - name: collector-textfiles
          readOnly: true
          mountPath: /run/prometheus
      - image: nvidia/dcgm-exporter:1.4.3
        name: nvidia-dcgm-exporter
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
        volumeMounts:
        - name: collector-textfiles
          mountPath: /run/prometheus

      hostNetwork: true
      hostPID: true

      volumes:
      - name: proc
        hostPath:
          path: /proc
      - name: sys
        hostPath:
          path: /sys
      - name: collector-textfiles
        emptyDir:
          medium: Memory
